ERROR    root:tasks.py:85 Reencryption c6863806-c126-44cb-87c6-9dd1a061a7ba: cannot process applet 7c427803-a4d1-4113-8ee2-be2448fac058, skip
ERROR    root:tasks.py:86 ERROR
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
  File "/usr/local/lib/python3.10/unittest/mock.py", line 2234, in _execute_mock_call
    raise effect
Exception: ERROR
ERROR    root:tasks.py:85 Reencryption c6863806-c126-44cb-87c6-9dd1a061a7ba: cannot process applet 7c427803-a4d1-4113-8ee2-be2448fac058, skip
ERROR    root:tasks.py:86 ERROR
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
  File "/usr/local/lib/python3.10/unittest/mock.py", line 2234, in _execute_mock_call
    raise effect
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
  File "/usr/local/lib/python3.10/unittest/mock.py", line 2234, in _execute_mock_call
    raise effect
Exception: ERROR