ERROR    root:tasks.py:85 Reencryption a9e8aa23-add7-4226-96c4-36ce710f5234: cannot process applet c55e9a94-2bb2-4686-bc40-e8efddd25f05, skip
ERROR    root:tasks.py:86 ERROR
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/mock.py", line 2240, in _execute_mock_call
    raise effect
Exception: ERROR
ERROR    root:tasks.py:85 Reencryption a9e8aa23-add7-4226-96c4-36ce710f5234: cannot process applet c55e9a94-2bb2-4686-bc40-e8efddd25f05, skip
ERROR    root:tasks.py:86 ERROR
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/mock.py", line 2240, in _execute_mock_call
    raise effect
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/mock.py", line 2240, in _execute_mock_call
    raise effect
Exception: ERROR