ERROR    root:tasks.py:85 Reencryption 9d9e3c75-8cc7-49f4-8054-305fdb9dca37: cannot process applet 43146537-130f-415e-bc29-1aaf14420646, skip
ERROR    root:tasks.py:86 ERROR
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
  File "/usr/local/lib/python3.10/unittest/mock.py", line 2234, in _execute_mock_call
    raise effect
Exception: ERROR
ERROR    root:tasks.py:85 Reencryption 9d9e3c75-8cc7-49f4-8054-305fdb9dca37: cannot process applet 43146537-130f-415e-bc29-1aaf14420646, skip
ERROR    root:tasks.py:86 ERROR
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
  File "/usr/local/lib/python3.10/unittest/mock.py", line 2234, in _execute_mock_call
    raise effect
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
  File "/usr/local/lib/python3.10/unittest/mock.py", line 2234, in _execute_mock_call
    raise effect
Exception: ERROR