ERROR    root:api.py:130 Answer creation failed: applet_id=7a9fe6ef-a930-46a2-8dd4-d757b178919b, user_id=7484f34a-3acc-4ee6-8a94-fd7299502fa1,                     activity_id=266bd370-ae39-4893-b09c-b13e1db78d66, error=ValidationError: Bad request.